name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: GymNotebook/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('GymNotebook/yarn.lock') }}
          restore-keys: node-modules-${{ runner.os }}-

      - name: Install apt deps (ninja & cmake)
        run: sudo apt-get update && sudo apt-get install -y ninja-build cmake

      - name: Install dependencies 
        working-directory: GymNotebook
        run: yarn install

      - name: Make gradlew executable
        working-directory: GymNotebook/android
        run: chmod +x gradlew
      
      - name: Install Android CMake
        run: yes | sdkmanager --install "cmake;3.22.1"

      - name: Clean Gradle build
        working-directory: GymNotebook/android
        run: ./gradlew clean

      - name: Build Debug APK
        working-directory: GymNotebook/android
        run: ./gradlew assembleDebug

      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: GymNotebook/android/app/build/outputs/apk/debug/app-debug.apk

      - name: Run tests
        working-directory: GymNotebook
        run: yarn test --coverage

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: GymNotebook/coverage
